name: Contributor Credits

on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Update Contributors
        uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          svgPath: docs/public/contributors.svg
          affiliation: all
          includeBots: false
          excludeUsers: hywax-assistant
          avatarSize: 96
          userNameHeight: 20
          svgWidth: 830
          commitMessage: 'chore: update CONTRIBUTORS'

  authors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Authors
        uses: wow-actions/update-authors@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          sort: 'commits'
          path: .github/AUTHORS.txt
          template: '{{ name }} <{{ email }}> - commits'
          commit: 'chore: update AUTHORS'
