name: Run Linters

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: ESLint
        run: pnpm run lint

      - name: Types
        run: pnpm run typecheck
